Feature/front main view activate
dnd-side-project/dnd-mentee-4th-8-mewe pull request #9
Opened 2021-01-30 09:16 UTC by lollin0

Added PopoverView.swift
Actived: MainView
 * 카테고리 버튼
 * 지도/캘린더로 가는 popover 버튼
 
![스크린샷 2021-01-30 오후 6 13 23](https://user-images.githubusercontent.com/43312096/106352482-d8139080-6326-11eb-827d-3f4ed74f0354.png)
![스크린샷 2021-01-30 오후 6 13 52](https://user-images.githubusercontent.com/43312096/106352486-e8c40680-6326-11eb-93b2-b631348bdbd9.png)

2021-02-01 12:22 UTC, dev-Lena requested changes
정빈님 PR 리뷰 남겼습니다! 🤓🤓

2021-02-01 12:22 UTC, dev-Lena commented on client/MEWE/MEWE/Category/View/CategoryView.swift
> +                    })
NavigationLink를 반복적으로 생성하는 것보다 text와 destination을 파라미터로 받아 NavigationLink를 생성하는 메서드를 만들어서 하는건 어떨까요? 그리고 destination은 enum으로 관리해도 좋을 것 같습니다!

2021-02-01 12:22 UTC, dev-Lena commented on client/MEWE/MEWE/ContentView.swift
> +        TodayView()
지난주 PR 리뷰가 반영되었군용! 😆

2021-02-01 12:22 UTC, dev-Lena commented on client/MEWE/MEWE/Today/View/CircleView.swift
> +                }
아직 모양만 잡은걸까요? button의 target과 button별 액션(버튼을 눌렀을 때 실행되는 메서드)는 어떻게 처리할 예정인지 궁금합니다 🤓

2021-02-01 12:22 UTC, dev-Lena commented on client/MEWE/MEWE/Today/View/SelectEmoji.swift
> +    @State var selectedTitles = Set<String>()
selectedTitles은 사용되는 곳이 없네요 이 프로퍼티는 어떤 역할인가요? 
그리고 데이터 타입을 Set으로 한 이유가 있나요? 네이밍만 봐서는 title(현재 제 추측으로는 '오늘의 한마디' 라고 생각하고 있어요)은 사용자가 중복되어서 작성할 수 있기 때문에 중복 값을 저장할 수 없는 Set이 적절한지 잘 모르겠어요!

2021-02-01 12:22 UTC, dev-Lena commented on client/MEWE/MEWE/Today/View/SelectEmoji.swift
> +                        Image(systemName: self.isPublic ? "lock.open" : "lock")
코드 보면서 생각난건데 프로젝트에서 사용하는 Image들의 이름을 Shared 폴더 안에 ImageName 파일을 만들어서 enum으로 선언해놓는 건 어떤가요? (제안입니다! 😃)

2021-02-01 12:22 UTC, dev-Lena commented on client/MEWE/MEWE/Today/View/TodayView.swift
> +                    }
여기서도 NavigationLink가 쓰였네요
혹시 NavigationLink 를 extension 해서 위에 남긴 코멘트처럼 파라미터를 받아 NavigationLink를 생성해서 리턴하는 메서드를 만들어서 사용하는건 어떨까요?

2021-02-01 12:22 UTC, dev-Lena commented on client/MEWE/MEWE/Today/ViewModel/PopoverView.swift
> +
PopoverView는 왜 ViewModel에 있는걸까요??
제가 몇 달전에 MVVM 공부하면서 [정리한 글](https://lena-chamna.netlify.app/post/ios_design_pattern_mvvm/#MVVM%EC%9D%98-%EA%B7%9C%EC%B9%99%EB%93%A4)이 있는데 제 생각에는 ViewModel은 View에 들어가는 데이터들을 관리하거나 관련된 기능을 하는 객체라고 생각해요. 그래서 PopoverView는 말 그대로 View 이기 때문에 ViewModel 로 분류하는게 적절하지 않은 것 같아요! 혹시 다른 의견 있으시면 자유롭게 말씀해주세요!👻

2021-02-04 07:24 UTC, lollin0 commented on client/MEWE/MEWE/Today/ViewModel/PopoverView.swift
> +
아 넵넵! 수정하겠습니다 ㅎㅎ

2021-02-04 07:26 UTC, lollin0 commented on client/MEWE/MEWE/Today/View/TodayView.swift
> +                    }
아 뭔가 제가 코드 쭉 작성하다가 나중에 리팩토링 하는 순서로 작업해와서 ㅠㅠㅋㅋㅋ 이게 혼자 할 때만 편하고 리뷰할 때에는 불편하겠네요 ㅠㅠ 변경해보겠습니다 😀

2021-02-04 07:26 UTC, lollin0 commented on client/MEWE/MEWE/Today/View/TodayView.swift
> +                    }
> 여기서도 NavigationLink가 쓰였네요
> 혹시 NavigationLink 를 extension 해서 위에 남긴 코멘트처럼 파라미터를 받아 NavigationLink를 생성해서 리턴하는 메서드를 만들어서 사용하는건 어떨까요?

아 뭔가 제가 코드 쭉 작성하다가 나중에 리팩토링 하는 순서로 작업해와서 ㅠㅠㅋㅋㅋ 이게 혼자 할 때만 편하고 리뷰할 때에는 불편하겠네요 ㅠㅠ 변경해보겠습니다 😀

2021-02-04 08:43 UTC, lollin0 commented on client/MEWE/MEWE/Today/View/SelectEmoji.swift
> +    @State var selectedTitles = Set<String>()
selectedTitles -> selectedEmojis로 수정하겠습니다! 이모지였어요 ㅎㅎ.,,

2021-02-04 12:21 UTC, dev-Lena approved these changes
머지하겠습니다~ 🥳

2021-02-04 12:21 UTC, dev-Lena commented on client/MEWE/MEWE/Today/View/TodayView.swift
> +                    }
아하! 그렇군요! 아 근데 먼저 쭉 구현하고 나중에 리팩토링하는 것도 좋은것 같아요! 정빈님 편하신 구현 방식대로 해주시면 될 것 같아요! 추후 수정 / 리팩토링할 예정인 부분은 주석으로 남겨주시거나 PR 디스크립션에 남기면 리뷰할 때 참고하겠습니다! 👻

2021-02-04 12:21 UTC, dev-Lena commented on client/MEWE/MEWE/Today/View/SelectEmoji.swift
> +    @State var selectedTitles = Set<String>()
아하! 넹넹! 👍🏻 중복된 이모지는 선택할 수 없으니 Set이 적절하겠네요!

2021-02-04 12:21 UTC, merged